# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae129f086a9a991fb0ea263633736c4e98da2d14372cefd1c80e4415dfa425f0b1612fa32e33e7c020175a06b33fbad77048f10627b2f39b39fbdeb7ee83ee87

test:
  secret_key_base: 76f7da5c08769f4c82a8e58b0591f20c26c945cb31401e8b9cad816821cbae6a8be3cf5c2177b5c6c9db2db81b057d8eb5237b77658e291f80829f1185501ac4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
